name: Cross-repository compatibility
on:
  push:
  pull_request:
jobs:
  compatibility:
    uses: cubacadabra/tools/.github/workflows/compatibility-reusable.yml@main
    with: { web_ref: ${{ github.sha }} }
